name: spigot-slack
version: 1.0.0
author: bittiez
main: US.bittiez.slackspigot
commands:
    SSReload:
        description: This will reload the config.
        usage: /SSReload
        permission: spigotslack.reload
permissions:
    spigotslack.reload:
        description: This will reload the config.
    spigotslack.ignore:
        description: Anyone with this permission will not have their messages sent to slack.
    spigotslack.silent:
        description: Anyone with this perm will not have any join or quit messages sent to slack.