slack-bot-token: ""

chat-channel: ""
chat-format: "[MSG]"
first-join-format: "Welcome [PLAYER] to the server!"
normal-join-format: "[PLAYER] has logged in."
player-quit-format: "[PLAYER] has left the server."
player-advancement-format: "[PLAYER] has earned the advancement: [ADVANCEMENT]"

#These are the slack channels that will be sent to the server chat:
incoming-channels: ["chan1", "chan2"]
incoming-chat-format: "[[CHANNEL]][DISPLAYNAME]: [MSG]"

#ignore these ids from slack
ignore-ids: [""]

#Ignore messages with attachments
ignore-attachments: false

#remove mentions? (If false, mentions will be sent to minecraft
remove-mentions: false

#Set to false if you don't want to send console messages to Slack
enable-console: true
console-channel: "console-chan"
console-avatar-url: ""